name: 'Dockerfile'
on:
  push:
    branches:
      - main
    paths:
      - 'Dockerfile'
jobs:
  dockerfile:
    name: 'Dockerfile'
    runs-on: ubuntu-latest
    steps:
      - 
        uses: brpaz/hadolint-action@v1.2.1
        with:
          dockerfile: Dockerfile
