name: Docker

on:
  schedule:
    - cron:  '0 0 * * 0'
  push:
    branches:
      - main
    paths:
      - '.hadolint.yaml'
      - 'Dockerfile'
      - '.github/workflows/main.yml'

  pull_request:

env:
  IMAGE_NAME: toolbox
  BUILD_ARCHS: "linux/arm/v7,linux/arm64,linux/amd64"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Lint
        uses: brpaz/hadolint-action@v1.2.1

  push:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/toolbox:latest
